## Import des librairies

In [220]:
import pandas as pd
import numpy as np # type: ignore
from sklearn.linear_model import LogisticRegression, LinearRegression # type: ignore
from sklearn.model_selection import train_test_split # type: ignore
from sklearn.metrics import mean_squared_error, precision_score # type: ignore
from joblib import dump,load # type: ignore
from sklearn.preprocessing import StandardScaler # type: ignore
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import scipy.stats

## Visualisation du csv

In [221]:
df = pd.read_csv('/Users/rakharrs/Developer/codage_TSINJO/CodageML/data/mydata.csv')
df

,language,uniquely_decodable,nbr_code,avg_length,min_length,max_length,length_ecartype,freq_0,freq_1,freq_p_0,...,freq_1_1,freq_1_2,freq_1_3,freq_1_4,freq_1_5,freq_1_6,freq_1_7,freq_1_8,freq_1_9,freq_1_10
0,"000000,001100,010010,101001,101100,101110,1110...",1,8,6.000000,0,6,0.000000,3.000000,3.000000,12.500000,...,3,2,0,2,3,4,5,5,0,0
1,"0,001110,0101001,011011,0111,1,10,100,11001,11...",0,10,4.100000,0,7,4.490000,1.800000,2.300000,10.000000,...,3,3,3,4,1,4,1,0,3,1
2,"001000,001100,010011,101001,111001",1,5,6.000000,0,6,0.000000,3.400000,2.600000,20.000000,...,2,3,3,4,1,0,0,0,0,0
3,"0,010110,1,1100111,1101",0,5,3.800000,0,7,6.160000,1.400000,2.400000,20.000000,...,3,5,3,0,1,0,0,0,0,0
4,"000011,000110,010101,100010,100101,100110,1110...",1,8,6.000000,0,6,0.000000,3.000000,3.000000,12.500000,...,3,2,3,4,2,2,5,3,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"0,00,0001,01,010010,0101,110111,11100",0,8,3.750000,0,6,3.187500,2.000000,1.750000,12.500000,...,5,2,2,3,1,0,1,0,0,0
9996,"001001,010100,010101",1,3,6.000000,0,6,0.000000,3.666667,2.333333,33.333333,...,2,3,2,0,0,0,0,0,0,0
9997,"00,001000,01,01001,0110111,1,10,1001101,101,110",0,10,3.800000,0,7,4.560000,1.900000,1.900000,10.000000,...,4,1,2,0,1,1,5,2,2,1
9998,"000111,001011,010010,011110,011111,101110,1100...",1,9,6.000000,0,6,0.000000,2.444444,3.555556,11.111111,...,4,2,3,5,3,4,2,6,3,0
9999,"0,0000,0001010,1,10,10001,1000100,1001,101",0,9,3.777778,0,7,4.617284,2.444444,1.333333,11.111111,...,2,1,2,0,0,2,2,2,1,0

In [297]:
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier


# put all column of df in X
X = df[['nbr_code','avg_length',
    'min_length', 'max_length', 'length_ecartype',
    'freq_0', 'freq_1', 
    'freq_p_0', 'freq_p_1',
    # 'freq_p_0_1', 'freq_p_0_2', 'freq_p_0_3', 'freq_p_0_4', 'freq_p_0_5',
    # 'freq_p_0_6', 'freq_p_0_7', 'freq_p_0_8', 'freq_p_0_9', 'freq_p_0_10',
    # 'freq_p_1_1', 'freq_p_1_2', 'freq_p_1_3', 'freq_p_1_4', 'freq_p_1_5',
    # 'freq_p_1_6', 'freq_p_1_7', 'freq_p_1_8', 'freq_p_1_9', 'freq_p_1_10',

    'freq_0_1', 'freq_0_2', 'freq_0_3', 'freq_0_4', 'freq_0_5',
    'freq_0_6', 'freq_0_7', 'freq_0_8', 'freq_0_9', 'freq_0_10',
    'freq_1_1', 'freq_1_2', 'freq_1_3', 'freq_1_4', 'freq_1_5',
    'freq_1_6', 'freq_1_7', 'freq_1_8', 'freq_1_9', 'freq_1_10',
        ]]

Y = df['uniquely_decodable']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.50, random_state=42)

model = LogisticRegression(max_iter=5000)
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

In [298]:
accuracy_score(Y_test, Y_pred) * 100

99.9

In [305]:
from modelGeneration import generate_model_row
from sardinasPatterson import IsUniquelyDecodable
columns = [
    'language', 'uniquely_decodable', 'nbr_code', 'avg_length',
    'min_length', 'max_length', 'length_ecartype',
    'freq_0', 'freq_1', 
    'freq_p_0', 'freq_p_1',
    'freq_p_0_1', 'freq_p_0_2', 'freq_p_0_3', 'freq_p_0_4', 'freq_p_0_5',
    'freq_p_0_6', 'freq_p_0_7', 'freq_p_0_8', 'freq_p_0_9', 'freq_p_0_10',
    'freq_p_1_1', 'freq_p_1_2', 'freq_p_1_3', 'freq_p_1_4', 'freq_p_1_5',
    'freq_p_1_6', 'freq_p_1_7', 'freq_p_1_8', 'freq_p_1_9', 'freq_p_1_10',

    'freq_0_1', 'freq_0_2', 'freq_0_3', 'freq_0_4', 'freq_0_5',
    'freq_0_6', 'freq_0_7', 'freq_0_8', 'freq_0_9', 'freq_0_10',
    'freq_1_1', 'freq_1_2', 'freq_1_3', 'freq_1_4', 'freq_1_5',
    'freq_1_6', 'freq_1_7', 'freq_1_8', 'freq_1_9', 'freq_1_10',
]
code = {'0000','001'}
b = pd.DataFrame([generate_model_row(code)], columns=columns)
# b
b.pop('language')
b.pop('uniquely_decodable')
# b.pop('nbr_code')
# b.pop('freq_p_0')
# b.pop('freq_p_1')
# b.pop('freq_0')
# b.pop('freq_1')

b.pop('freq_p_0_1')
b.pop('freq_p_0_2')
b.pop('freq_p_0_3')
b.pop('freq_p_0_4')
b.pop('freq_p_0_5')

b.pop('freq_p_0_6')
b.pop('freq_p_0_7')
b.pop('freq_p_0_8')
b.pop('freq_p_0_9')
b.pop('freq_p_0_10')

b.pop('freq_p_1_1')
b.pop('freq_p_1_2')
b.pop('freq_p_1_3')
b.pop('freq_p_1_4')
b.pop('freq_p_1_5')

b.pop('freq_p_1_6')
b.pop('freq_p_1_7')
b.pop('freq_p_1_8')
b.pop('freq_p_1_9')
b.pop('freq_p_1_10')

# b.pop('freq_0_1')
# b.pop('freq_0_2')
# b.pop('freq_0_3')
# b.pop('freq_0_4')
# b.pop('freq_0_5')
# 
# b.pop('freq_0_6')
# b.pop('freq_0_7')
# b.pop('freq_0_8')
# b.pop('freq_0_9')
# b.pop('freq_0_10')
# 
# b.pop('freq_1_1')
# b.pop('freq_1_2')
# b.pop('freq_1_3')
# b.pop('freq_1_4')
# b.pop('freq_1_5')
# 
# b.pop('freq_1_6')
# b.pop('freq_1_7')
# b.pop('freq_1_8')
# b.pop('freq_1_9')
# b.pop('freq_1_10')
print(IsUniquelyDecodable(code))
bool(model.predict(b)[0])

True

True

In [94]:
df = pd.read_csv('/Users/rakharrs/Developer/codage_TSINJO/CodageML/data/mydata.csv')
df

,language,uniquely_decodable,nbr_code,avg_length,min_length,max_length,length_ecartype,freq_0,freq_1,freq_0_1,...,freq_1_1,freq_1_2,freq_1_3,freq_1_4,freq_1_5,freq_1_6,freq_1_7,freq_1_8,freq_1_9,freq_1_10
0,"0100,01110,10001,1010,101000,11,1100",1,7,4.285714,0,6,1.346939,14.285714,14.285714,12.500000,...,14.285714,14.285714,14.285714,7.142857,14.285714,21.428571,14.285714,0.000000,0.000000,0.000000
1,"0,00,001,011,0110100,0111,1,1011,110,111100",0,10,3.400000,0,7,3.440000,10.000000,10.000000,0.000000,...,5.263158,10.526316,21.052632,15.789474,15.789474,15.789474,10.526316,0.000000,5.263158,0.000000
2,"011,1100100",1,2,5.000000,0,7,4.000000,50.000000,50.000000,20.000000,...,40.000000,60.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,"0,00001,000010,00111,01,011,0110,01110,1,1111",0,10,3.600000,0,6,2.840000,10.000000,10.000000,0.000000,...,5.555556,11.111111,5.555556,5.555556,11.111111,5.555556,16.666667,0.000000,22.222222,16.666667
4,"000001,01101,1000110",1,3,6.000000,0,7,0.666667,33.333333,33.333333,18.181818,...,42.857143,14.285714,42.857143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11404,"10,11",1,2,2.000000,0,2,0.000000,50.000000,50.000000,0.000000,...,66.666667,33.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11405,"000,001011,01,01010,01100,10,11,111100",0,8,3.875000,0,6,2.859375,12.500000,12.500000,18.750000,...,13.333333,0.000000,26.666667,13.333333,6.666667,6.666667,20.000000,13.333333,0.000000,0.000000
11406,"0010101,0111111,100,110,1100111",1,5,5.400000,0,7,3.840000,20.000000,20.000000,10.000000,...,11.764706,29.411765,35.294118,5.882353,17.647059,0.000000,0.000000,0.000000,0.000000,0.000000
11407,"001,0010,00101,10,1001,101001",0,6,4.000000,0,6,1.666667,16.666667,16.666667,21.428571,...,20.000000,30.000000,10.000000,20.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000
11408,"00011,110111,11101,111110",1,4,5.500000,0,6,0.250000,25.000000,25.000000,50.000000,...,12.500000,25.000000,31.250000,31.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [40]:
from modelGeneration import set_to_string
c = {'01','101'}
print(set_to_string(c))
generate_model_row({'01'})[0]

01,101

'01'

In [303]:
import joblib

In [307]:
joblib.dump(model, '/Users/rakharrs/Developer/codage_TSINJO/CodageML/data/model.pkl')

['/Users/rakharrs/Developer/codage_TSINJO/CodageML/data/model.pkl']